import math

import a34_exception

a34_exception.Myerror

def main():
    math.tan()
    math.sin

if __name__ == "__main__":
    main()


